export const AUDIO_PLACEHOLDER_INTRO = 'AUDIO_PLACEHOLDER_INTRO';
export const AUDIO_PLACEHOLDER_COMPLETE = 'AUDIO_PLACEHOLDER_COMPLETE';
export const AUDIO_PLACEHOLDER_ARTIFACT = 'AUDIO_PLACEHOLDER_ARTIFACT';
