// Centralized theme config for Prison Ready
import { colors } from './colors';

export const themes: {
  [key: string]: {
    key: string;
    label: string;
    colors: typeof colors & Record<string, string>;
    labels: Record<string, string>;
    backgroundType: string;
  };
} = {
  prison: {
    key: 'prison',
    label: 'Prison',
    colors: {
      background: colors.background,
      card: colors.cardBg,
      cardBg: colors.cardBg,
      surface: colors.surface,
      border: colors.border,
      prisonOrange: colors.prisonOrange,
      prisonOrangeDark: colors.prisonOrangeDark,
      gold: colors.gold,
      xp: colors.xp,
      teal: colors.teal,
      accentTeal: colors.accentTeal,
      purple: colors.purple,
      text: colors.text,
      textSecondary: colors.textSecondary,
      success: colors.success,
      danger: colors.danger,
      glowOrange: colors.glowOrange,
      glowGold: colors.glowGold,
      glowPurple: colors.glowPurple,
      white: colors.white,
      black: colors.black,
      charcoal: colors.charcoal,
      slate: colors.slate,
      cardBorder: colors.cardBorder,
      incomplete: colors.incomplete,
      complete: colors.complete,
      accent: colors.prisonOrange,
      accentGlow: colors.glowOrange,
      streak: colors.prisonOrange,
      streakGlow: colors.glowOrange,
    },
    labels: {
      streak: 'Current Bid',
      badge: 'Badge',
      mission: 'Job',
      progress: 'Progress',
      health: 'Health Sync',
    },
    backgroundType: 'gradient',
  },
  mystery: {
    key: 'mystery',
    label: 'Mystery',
    colors: {
      background: colors.background,
      card: colors.cardBg,
      cardBg: colors.cardBg,
      surface: colors.surface,
      border: colors.border,
      prisonOrange: colors.prisonOrange,
      prisonOrangeDark: colors.prisonOrangeDark,
      gold: colors.gold,
      xp: colors.xp,
      teal: colors.teal,
      accentTeal: colors.accentTeal,
      purple: colors.purple,
      text: colors.text,
      textSecondary: colors.textSecondary,
      success: colors.success,
      danger: colors.danger,
      glowOrange: colors.glowOrange,
      glowGold: colors.glowGold,
      glowPurple: colors.glowPurple,
      white: colors.white,
      black: colors.black,
      charcoal: colors.charcoal,
      slate: colors.slate,
      cardBorder: colors.cardBorder,
      incomplete: colors.incomplete,
      complete: colors.complete,
      accent: colors.purple,
      accentGlow: colors.glowPurple,
      streak: colors.purple,
      streakGlow: colors.glowPurple,
    },
    labels: {
      streak: 'Case Streak',
      badge: 'Medal',
      mission: 'Investigation',
      progress: 'Progress',
      health: 'Health Sync',
    },
    backgroundType: 'gradient',
  },
};
